# author: tim.schaefer.de@gmail.com
# edited for my nextcloud
# 

services:
  db:
    image: ${DB_DOCKER_IMAGE}
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./db/mysql:/var/lib/mysql
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_user_password
      - mysql_database

  redis:
    image: redis:alpine
    container_name: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PW}
    
  web:
    restart: unless-stopped
    image: ${WEB_DOCKER_IMAGE}
    container_name: ${WEB_CONTAINER_NAME}
    depends_on:
      - db
      - redis
    networks:
      - default
      - proxy_net
    ports:
      - 8480:80
    environment:
      TZ: Europe/Berlin
      
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/nextcloud_admin_password
      # Nextcloud trusted domains
      NEXTCLOUD_TRUSTED_DOMAINS: ${HOST}
      # Nextcloud data path
      NEXTCLOUD_DATA_DIR: /var/www/html/data
      NEXTCLOUD_TABLE_PREFIX: oc_
      # SMTP Mail setup:
      SMTP_HOST: smtp.gmail.com
      SMTP_SECURE: ssl
      SMTP_PORT: 465
      SMTP_AUTHTYPE: LOGIN
      SMTP_NAME: ${EMAIL}
      # the follwing are set in the mail_pw.env file
      #SMTP_PASSWORD: 
      #MAIL_FROM_ADDRESS: compass.cloud.dev
      #MAIL_DOMAIN: gmail.com

      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_PW}

      MYSQL_HOST: db
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
    env_file:
      - ./mail_pw.env
    volumes:
      - ./nextcloud_main:/var/www/html/
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      - ./php/nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
      - /mnt/photos_hdd/:/mnt/photo_hdd_nc/
    secrets:
      - nextcloud_admin_password
      - mysql_user
      - mysql_user_password
      - mysql_database

  cron:
    image: ${WEB_DOCKER_IMAGE}
    container_name: ${CRON_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_PW}
    volumes:
      - ./nextcloud_main:/var/www/html/
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      - ./php/nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini:ro
      - /mnt/photos_hdd/:/mnt/photo_hdd_nc/
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis


  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - default
    mem_limit: 2048m

  
  # admin software
  #adminer:
  #  image: adminer
  #  restart: unless-stopped
  #  ports:
  #    - 8787:8080


networks:
    proxy_net:
         name: ${NETWORK}
         external: true

secrets:
  nextcloud_admin_password:
    file: ./nextcloud_admin_password.secret
  mysql_root_password:
    file: ./mysql_root_password.secret
  mysql_user:
    file: ./mysql_user.secret
  mysql_user_password:
    file: ./mysql_user_password.secret
  mysql_database:
    file: ./mysql_database.secret

